language: bash
sudo: true
install:
  - sudo apt -y install python3 python3-pip build-essential python3-dev
  - sudo pip3 install --upgrade pip
  - pip3 install -q --user jupyter jupyter_contrib_nbextensions 
  - jupyter contrib nbextension install --user
script:
  - (find -type f -iregex .*\.ipynb; find -type f -iregex .*-checkpoint\.ipynb) | sort | uniq -u | jupyter nbconvert --template toc2
