language: bash
sudo: true
install:
  - sudo apt -y install miniconda
  - sudo conda install -q jupyter
  - sudo conda install -c conda-forge jupyter_contrib_nbextensions
  - sudo jupyter contrib nbextension install --system
  - sudo jupyter nbextension enable toc2/main
script:
  - (find -type f -iregex .*\.ipynb; find -type f -iregex .*-checkpoint\.ipynb) | sort | uniq -u | jupyter nbconvert --template toc2
