language: bash
sudo: true
before_install:
  - apt install python3 python3-pip
install:
  - sudo pip3 install jupyter jupyter_contrib_nbextensions
  - sudo jupyter contrib nbextension install --system
script:
  - (find -type f -iregex .*\.ipynb; find -type f -iregex .*-checkpoint\.ipynb) | sort | uniq -u | jupyter nbconvert --template toc2
