language: python
python:
  - "3.6"
install:
  # Install miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION 
  - source activate test-environment
  - conda install jupyter
  - conda install -c conda-forge jupyter_contrib_nbextensions
  - jupyter contrib nbextension install --user
  - jupyter nbextension enable toc2/main

script:
  # Export the notebooks to html
  - (find -type f -iregex .*\.ipynb; find -type f -iregex .*-checkpoint\.ipynb) | 
      sort | 
      uniq -u | 
      xargs jupyter nbconvert --template toc2 --to html --output-dir Public-visu 
  # Generating descriptive homepage
  - bash ./description_generator.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token:  46a2f969f4826293113421f8ca7860b8dc9bcea3 
  keep-history: true
  local-dir: Public-visu
  on:
    branch: master

